#!/bin/bash

# Forked from https://github.com/depsterr/mfetch by Zac the Wise
# I'm a beginner in bash scripting, I saw a lovely 'fetch' tool
# and noticed it didn't have support for Mac OS, the goal is
# to provide a similar tool for Mac users.

# read system info
host=$(hostname)

# get OS name and version
os_name=$(sw_vers | awk 'NR==1{print $2 " " $3 " " $4}')
os_ver=$(sw_vers | awk 'NR==2{print $2 " " $3 " " $4}')

# get kernel name and version
kernel=$(uname -rs)

# Get terminal
term_full="$TERM ${TERM_PROGRAM//_/ }"
terminal=$(echo $term_full | awk '{print $2 " " $3 " " $4}')

# Colors and palette method taken from dylanaraps pftech
# https://github.com/dylanaraps/pfetch
c0='[0m';
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'
gray='[38;5;240m'
palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 [m"

# Output
cat << EOF
${gray}$(uptime) 
${c5}                          ${USER}${c0}@${c5}${host}
${c5}        |\__/,|   (\`\     ${c6}os${c0}        ${os_name} ${os_ver}
${c5}      _.|${c4}o o${c5}  |_   ) )    ${ARTR3}${c6}kernel${c0}    ${kernel}
${c5}    ${c4}-${c5}(((${c4}---${c5}(((${c4}--------    ${c6}shell${c0}     ${SHELL##*/}

${c5}                                         ${palette}
EOF